/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calculator;
import java.util.ArrayList;

/**
 *
 * @author vitor
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backspace = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        rightp = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        equal = new javax.swing.JButton();
        leftp = new javax.swing.JButton();
        area = new javax.swing.JTextField();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        backspace.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        backspace.setText("delete");
        backspace.setMargin(new java.awt.Insets(19, 19, 19, 19));
        backspace.addActionListener(this::backspaceActionPerformed);

        btn0.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn0.setText("0");
        btn0.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn0.addActionListener(this::btnActionStandart);

        btn1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn1.setText("1");
        btn1.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn1.addActionListener(this::btnActionStandart);

        btn2.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn2.setText("2");
        btn2.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn2.addActionListener(this::btnActionStandart);

        btn3.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn3.setText("3");
        btn3.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn3.addActionListener(this::btnActionStandart);

        btn4.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn4.setText("4");
        btn4.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn4.addActionListener(this::btnActionStandart);

        btn5.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn5.setText("5");
        btn5.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn5.addActionListener(this::btnActionStandart);

        btn6.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn6.setText("6");
        btn6.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn6.addActionListener(this::btnActionStandart);

        btn7.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn7.setText("7");
        btn7.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn7.addActionListener(this::btnActionStandart);

        btn8.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn8.setText("8");
        btn8.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn8.addActionListener(this::btnActionStandart);

        btn9.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn9.setText("9");
        btn9.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn9.addActionListener(this::btnActionStandart);

        rightp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        rightp.setText(")");
        rightp.setMargin(new java.awt.Insets(19, 19, 19, 19));
        rightp.addActionListener(this::btnActionStandart);

        clear.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        clear.setText("C");
        clear.setMargin(new java.awt.Insets(19, 19, 19, 19));
        clear.addActionListener(this::clearActionPerformed);

        equal.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        equal.setText("=");
        equal.setMargin(new java.awt.Insets(19, 19, 19, 19));
        equal.addActionListener(this::equalActionPerformed);

        leftp.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        leftp.setText("(");
        leftp.setMargin(new java.awt.Insets(19, 19, 19, 19));
        leftp.addActionListener(this::btnActionStandart);

        btn10.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn10.setText("+");
        btn10.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn10.addActionListener(this::btnActionStandart);

        btn11.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn11.setText("-");
        btn11.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn11.addActionListener(this::btnActionStandart);

        btn12.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn12.setText("*");
        btn12.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn12.addActionListener(this::btnActionStandart);

        btn13.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        btn13.setText("/");
        btn13.setMargin(new java.awt.Insets(19, 19, 19, 19));
        btn13.addActionListener(this::btnActionStandart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn1)
                                    .addComponent(clear)
                                    .addComponent(btn4)
                                    .addComponent(btn7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn0)
                                    .addComponent(btn2)
                                    .addComponent(btn5)
                                    .addComponent(btn8)))
                            .addComponent(backspace, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(leftp)
                                .addGap(18, 18, 18)
                                .addComponent(rightp))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn9)
                                    .addComponent(equal)
                                    .addComponent(btn3)
                                    .addComponent(btn6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn11)
                                    .addComponent(btn10)
                                    .addComponent(btn12)
                                    .addComponent(btn13))))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(area, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftp)
                    .addComponent(rightp)
                    .addComponent(backspace))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn7)
                            .addComponent(btn8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn4)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn1)
                                    .addComponent(btn2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(clear)
                                    .addComponent(btn0)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn9)
                            .addComponent(btn10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn6)
                            .addComponent(btn11))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn3)
                            .addComponent(btn12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(equal)
                            .addComponent(btn13))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private double calculateWithParentheses(String expression) {
        while (expression.contains("(")) {

            int start = expression.lastIndexOf("(");
            int end = expression.indexOf(")", start);

            if (end == -1) {
                throw new IllegalArgumentException("Parênteses inválidos");
            }

            String inside = expression.substring(start + 1, end);

            double result = calculateExpression(inside);

            expression = expression.substring(0, start)
                       + result
                       + expression.substring(end + 1);
        }

        return calculateExpression(expression);
    }
    
    private double calculateExpression(String expression) {
        ArrayList<Double> numbers = new ArrayList<>();
        ArrayList<Character> operators = new ArrayList<>();

        String currentNumber = "";

        // 1. Separar números e operadores
        for (int i = 0; i < expression.length(); i++) {
            char c = expression.charAt(i);

            if (Character.isDigit(c) || c == '.') {
                currentNumber += c;
            } else if (c == '+' || c == '-' || c == '*' || c == '/') {
                numbers.add(Double.parseDouble(currentNumber));
                operators.add(c);
                currentNumber = "";
            }
        }

        // adiciona o último número
        numbers.add(Double.parseDouble(currentNumber));

        // 2. Resolver * e /
        int i = 0;
        while (i < operators.size()) {
            char op = operators.get(i);

            if (op == '*' || op == '/') {
                double a = numbers.get(i);
                double b = numbers.get(i + 1);
                double parcial;

                if (op == '*') {
                    parcial = a * b;
                } else {
                    if (b == 0) {
                        throw new ArithmeticException("Divisão por zero");
                    }
                    parcial = a / b;
                }

                numbers.set(i, parcial);
                numbers.remove(i + 1);
                operators.remove(i);
            } else {
                i++;
            }
        }

        // 3. Resolver + e -
        double resultado = numbers.get(0);

        for (int j = 0; j < operators.size(); j++) {
            char op = operators.get(j);

            if (op == '+') {
                resultado += numbers.get(j + 1);
            } else if (op == '-') {
                resultado -= numbers.get(j + 1);
            }
        }

        return resultado;
    }
    
    private void btnActionStandart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionStandart
        // TODO add your handling code here:
        javax.swing.JButton btn = (javax.swing.JButton) evt.getSource();
        area.setText(area.getText() + btn.getText());
    }//GEN-LAST:event_btnActionStandart

    private void backspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backspaceActionPerformed
        // TODO add your handling code here:
        String text = area.getText();

        if (text.length() > 0) {
            text = text.substring(0, text.length() - 1);
            area.setText(text);
        }
    }//GEN-LAST:event_backspaceActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        area.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void equalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalActionPerformed
        // TODO add your handling code here:
        try {
            String expression = area.getText();
            double result = calculateWithParentheses(expression);
            area.setText(String.valueOf(result));
        } catch (Exception e) {
            area.setText("Error");
        }
    }//GEN-LAST:event_equalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Main().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField area;
    private javax.swing.JButton backspace;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton clear;
    private javax.swing.JButton equal;
    private javax.swing.JButton leftp;
    private javax.swing.JButton rightp;
    // End of variables declaration//GEN-END:variables
}
